# Generated by Django 4.2.17 on 2025-01-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee_Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EMP_NAME", models.CharField(max_length=500)),
                ("EMP_DESI", models.CharField(max_length=500)),
                ("EMP_PLACE", models.CharField(max_length=500)),
            ],
        ),
    ]
